[project]
name = "parsefire"
dynamic = ["version"]
license = "MIT"
description = "Python Package for consistent data mining from unstructured text documents."
keywords = ["Data mining", "Text Parsing"]
authors = [
    {name = "Michel Fodje", email = "michel.fodje@lightsource.ca" },
]
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]

[project.urls]
Homepage = "https://github.com/michel4j/parsefire"
Issues = "https://github.com/michel4j/parsefire/issues"

[tool.poetry]
packages = [
    { include = "parsefire", from = "." },
    { include = "tests", format = "sdist" },
]
version = "0.0.0"

[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "^6.0.0"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = ["plugin"] }

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
format = "{base}.{revision}{distance}"
